services:
  - type: web
    name: compri-school
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production